name: Build

on:
  workflow_call:
    inputs:
      project:
        required: true
        type: string

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4.1.0
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '5.x'
      - name: Install dependencies
        working-directory: ${{ inputs.project }}
        run: dotnet restore
      - name: Build project
        working-directory: ${{ inputs.project }}
        run: dotnet build
