name: PangLib.DAT (Build)

on:
  push:
    branches: [ master ]
    paths:
      - 'PangLib.DAT/**.*'
  pull_request:
    branches: [ master ]
    paths:
      - 'PangLib.DAT/**.*'

jobs:
  build:
    uses: ./.github/workflows/_build.yaml
    with:
      project: PangLib.DAT
