name: PangLib.IFF (Build)

on:
  push:
    branches: [ master ]
    paths:
      - 'PangLib.IFF/**.*'
  pull_request:
    branches: [ master ]
    paths:
      - 'PangLib.IFF/**.*'

jobs:
  build:
    uses: ./.github/workflows/_build.yaml
    with:
      project: PangLib.IFF
