name: PangLib.PAK (Build)

on:
  push:
    branches: [ master ]
    paths:
      - 'PangLib.PAK/**.*'
  pull_request:
    branches: [ master ]
    paths:
      - 'PangLib.PAK/**.*'

jobs:
  build:
    uses: ./.github/workflows/_build.yaml
    with:
      project: PangLib.PAK
