name: PangLib.PET (Build)

on:
  push:
    branches: [ master ]
    paths:
      - 'PangLib.PET/**.*'
  pull_request:
    branches: [ master ]
    paths:
      - 'PangLib.PET/**.*'

jobs:
  build:
    uses: ./.github/workflows/_build.yaml
    with:
      project: PangLib.PET
