name: PangLib.SBIN (Build)

on:
  push:
    branches: [ master ]
    paths:
      - 'PangLib.SBIN/**.*'
  pull_request:
    branches: [ master ]
    paths:
      - 'PangLib.SBIN/**.*'

jobs:
  build:
    uses: ./.github/workflows/_build.yaml
    with:
      project: PangLib.SBIN
