name: PangLib.Scripting (Build)

on:
  push:
    branches: [ master ]
    paths:
      - 'PangLib.Scripting/**.*'
  pull_request:
    branches: [ master ]
    paths:
      - 'PangLib.Scripting/**.*'

jobs:
  build:
    uses: ./.github/workflows/_build.yaml
    with:
      project: PangLib.Scripting
