name: PangLib.UCC (Build)

on:
  push:
    branches: [ master ]
    paths:
      - 'PangLib.UCC/**.*'
  pull_request:
    branches: [ master ]
    paths:
      - 'PangLib.UCC/**.*'

jobs:
  build:
    uses: ./.github/workflows/_build.yaml
    with:
      project: PangLib.UCC
