name: PangLib.UpdateList (Build)

on:
  push:
    branches: [ master ]
    paths:
      - 'PangLib.UpdateList/**.*'
  pull_request:
    branches: [ master ]
    paths:
      - 'PangLib.UpdateList/**.*'

jobs:
  build:
    uses: ./.github/workflows/_build.yaml
    with:
      project: PangLib.UpdateList
