name: PangLib.Utilities (Build)

on:
  push:
    branches: [ master ]
    paths:
      - 'PangLib.Utilities/**.*'
  pull_request:
    branches: [ master ]
    paths:
      - 'PangLib.Utilities/**.*'

jobs:
  build:
    uses: ./.github/workflows/_build.yaml
    with:
      project: PangLib.Utilities
