name: PangLib.WEP (Build)

on:
  push:
    branches: [ master ]
    paths:
      - 'PangLib.WEP/**.*'
  pull_request:
    branches: [ master ]
    paths:
      - 'PangLib.WEP/**.*'

jobs:
  build:
    uses: ./.github/workflows/_build.yaml
    with:
      project: PangLib.WEP
